trigger:
  - master

pr:
  - master

pool:
  vmImage: 'ubuntu-18.04'

steps:
  - script: docker build -t ansible-base-test-container .
    displayName: Build Container
  - script: docker history ansible-base-test-container
    displayName: Show History
